### ISSUE TITLE
Add a parser for dot (/branch etc) names

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/python-sdk#3]
User interfaces often let users input strings to identify:

- Dots
- Branches
- Subdots
- Subdot-on-branch

We use a standard syntax for this, the reference implementation of which is partly in the `dm` CLI (`ParseNamespacedVolume` in `cmd/dm/pkg/remotes/api.go`), partly in the procure mechanism (`cloneName` parsing in `reallyProcureFilesystem` in `cmd/dotmesh-server/controller.go`) and `parseNamespacedVolumeWithSubvolumes` ub `cmd/dotmesh-server/utils.go`.

Put a parser for it in the Python library, with different functions based on whether we expect just a dot name, or whether branches and/or subdots are also allowed.

**Comment by lukemarsden** [comment]
When we have this, we can replace https://github.com/dotmesh-io/python-sdk/commit/964f615f4e968896ea8555aaf97d6b3ce466a90d with the usage of this parser.

**Comment by lukemarsden** [comment]
Added support for namespaces and names, bumping the rest of the work to https://github.com/dotmesh-io/python-sdk/issues/4
